### ISSUE TITLE
Admin Site

### ISSUE THREAD

**Issue by Fun1628** [psemdel/py-trading-bot#41]
Please explain what each item does and the relation between them. Thanks.

Under Order Tab

Action Categories
Action sectors

I understand Action means Stock.

However, if I want IB to retrieve APPL market data, how do I go about doing that? How often can I retrieve the stock price

**Comment by psemdel** [comment]
https://github.com/psemdel/py-trading-bot/blob/main/docs/stocks.md
Action Categories: is to distinguish between stocks (that can be traded directly) and indexes (that cannot)
Action sectors: sector according to GICS classification of the product. Important for NYSE stocks, as otherwise they are too many

I should definitely rename Action into Stock someday, but I fear it will be very long to debug.

If you want to trade "often" you should use the "intraday" options. In the settings there is
"TIME_INTERVAL_INTRADAY":15,
Which is in minute, you could do it more often, but don't forget that IB is quite slow...

In reporting.telegram.py

            if _settings["INTRADAY"]:
                self.manager.every(_settings["TIME_INTERVAL_INTRADAY"], 'minutes').do(self.daily_report,s_ex=s_ex,intraday=True)

And so the "daily_report" will be executed every TIME_INTERVAL_INTRADAY.
The strategy you use on it, needs to be defined as "strategies_in_use_intraday" in each exchange.

**Comment by Fun1628** [comment]
when you have a chance, can you explain the other items in the admin site, thanks

**Comment by psemdel** [comment]
It should be in the docs.
